version: 43
jobs:
- name: Sync GitHub
  steps:
  - type: CheckoutStep
    name: checkout
    cloneCredential:
      type: DefaultCredential
    withLfs: false
    withSubmodules: false
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: sync
    runInContainer: true
    image: alpine/git:1.0.7
    interpreter:
      type: DefaultInterpreter
      commands: |
        git config --global --unset http.extraHeader
        git push -f https://raphaelschuhmann:@secret:GitHub-PAT@@@github.com/raphaelschuhmann/zenith.git
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: BranchUpdateTrigger
    userMatch: anyone
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 60
- name: Pull GitHub
  steps:
  - type: PullRepository
    name: pull
    remoteUrl: https://raphaelschuhmann:@secret:GitHub-PAT@@@github.com/raphaelschuhmann/zenith.git
    userName: RaphaelSchuhmann
    passwordSecret: GitHub-PAT
    accessTokenSecret: GitHub-PAT
    refs: refs/heads/* refs/tags/*
    withLfs: false
    force: false
    condition: SUCCESSFUL
    optional: false
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
