version: 43
jobs:
- name: Sync GitHub
  steps:
  - type: CheckoutStep
    name: checkout
    cloneCredential:
      type: DefaultCredential
    withLfs: false
    withSubmodules: false
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: sync
    runInContainer: true
    image: alpine/git:1.0.7
    interpreter:
      type: DefaultInterpreter
      commands: |
        git config --global --unset http.extraHeader
        git push -f https://raphaelschuhmann:@secret:GitHub-PAT@@@github.com/raphaelschuhmann/zenith.git
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: BranchUpdateTrigger
    userMatch: anyone
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 60
- name: Pull GitHub
  steps:
  - type: CheckoutStep
    name: checkout
    cloneCredential:
      type: DefaultCredential
    withLfs: false
    withSubmodules: false
    condition: ALWAYS
    optional: false
  - type: CommandStep
    name: Pull
    runInContainer: true
    image: alpine/git:1.0.7
    interpreter:
      type: DefaultInterpreter
      commands: |
        git config --global --unset http.extraHeader
        git pull -f https://raphaelschuhmann:@secret:GitHub-PAT@@@github.com/raphaelschuhmann/zenith.git
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: ScheduleTrigger
    cronExpression: 0 0/15 * * * ?
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
